site_name: Jumpstart Learning Resources
repo_url: https://github.com/Code-4-Community/Teaching-Resources

theme:
  name: material
  favicon: "img/favicon.ico"
  features:
    - tabs

nav:
  - Home: index.md
  - Jumpstart Docs:
      - Home: jumpstart/index.md
      - Jumpstart Dictionary: jumpstart/dictionary.md
      - Important Links for Jumpstart: jumpstart/important_links.md
      - "Week 1: Project Overview and Terminal Basics": jumpstart/week-1.md
      - "Week 1.5: Version Control and Git": jumpstart/week-1.5-git.md
      - "Week 2: Introduction to HTML and CSS": jumpstart/week-2.md
      - "Week 3: Introduction to Javascript": jumpstart/week-3.md
      - "Week 4: React": jumpstart/week-4.md
  - Guides:
      - Home: guides/index.md
      - Send a POST request: guides/postrequest.md
  - Workshops (2019):
      - Home: workshops2019/index.md
      - Frontend Web Development and Vue.js: workshops2019/frontend/index.md
      - Intro To Backend Development and APIs: workshops2019/backend/index.md
